# Generated by Django 6.0.4 on 2026-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='coach_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='coach_private_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
