# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('checks', '0006_migrate_legacy_question_types'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignedcheck',
            index=models.Index(fields=['client', 'is_active'], name='checks_assi_client__c9a8da_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedcheck',
            index=models.Index(fields=['coach', 'is_active'], name='checks_assi_coach_i_36c3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedcheckinstance',
            index=models.Index(fields=['assignment', '-due_date'], name='checks_assi_assignm_deab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedcheckinstance',
            index=models.Index(fields=['status', 'expires_at'], name='checks_assi_status_de8359_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['client', '-captured_at'], name='checks_prog_client__2eecdd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['coach', 'status'], name='checks_ques_coach_i_f4d4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['client', 'coach', '-submitted_at'], name='checks_ques_client__f27104_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['client', '-submitted_at'], name='checks_ques_client__fb14a5_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['coach', '-created_at'], name='checks_ques_coach_i_3b0416_idx'),
        ),
    ]
