# Generated by Django 6.0.4 on 2026-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0009_remap_measurement_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='questions_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='steps_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
