# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('calendar', '0002_appointment_is_recurring_appointment_recurrence_rule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['coach', 'start_datetime'], name='calendar_ap_coach_i_c32a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start_datetime'], name='calendar_ap_client__a26ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_datetime'], name='calendar_ap_status_61ff7d_idx'),
        ),
    ]
