# Generated by Django 6.0.4 on 2026-05-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('APPOINTMENT_REQUEST', 'Appointment Request'), ('APPOINTMENT_ACCEPTED', 'Appointment Accepted'), ('APPOINTMENT_REJECTED', 'Appointment Rejected'), ('CHECK_SUBMITTED', 'Check Submitted'), ('CHECK_REVIEWED', 'Check Reviewed'), ('WORKOUT_ASSIGNED', 'Workout Assigned'), ('NUTRITION_ASSIGNED', 'Nutrition Plan Assigned'), ('SUPPLEMENT_ASSIGNED', 'Supplement Sheet Assigned')], max_length=50),
        ),
    ]
