# Generated by Django 6.0.4 on 2026-05-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('chat', '0003_conversation_chat_conver_last_me_31163c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WELCOME', 'Benvenuto'), ('GOODBYE', 'Arrivederci'), ('SUBSCRIPTION_EXPIRING', 'Abbonamento in scadenza')], max_length=30)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='automatic_messages/')),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_message_templates', to='accounts.coachprofile')),
            ],
            options={
                'unique_together': {('coach', 'event_type')},
            },
        ),
    ]
