# Generated by Django 6.0.4 on 2026-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticmessagetemplate',
            name='event_type',
            field=models.CharField(choices=[('WELCOME', 'Benvenuto'), ('GOODBYE', 'Arrivederci'), ('SUBSCRIPTION_EXPIRING', 'Abbonamento in scadenza'), ('PLAN_DELETED', 'Scheda eliminata')], max_length=30),
        ),
    ]
