# Generated by Django 6.0.4 on 2026-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=16)),
                ('phase', models.CharField(blank=True, default='', max_length=32)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_import_job',
                'indexes': [models.Index(fields=['created_at'], name='shared_impo_created_badee0_idx')],
            },
        ),
    ]
