# Generated by Django 6.0.4 on 2026-05-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_clientprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChironMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('used_web_search', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiron_messages', to='accounts.user')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chiron_chir_user_id_474a43_idx')],
            },
        ),
    ]
