# Generated by Django 6.0.4 on 2026-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chironmessage',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
