# Generated by Django 6.0.4 on 2026-06-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_devicetoken_bundle_id'),
        ('chiron', '0002_chironmessage_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChironSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_up_to_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chiron_summary', to='accounts.user')),
            ],
        ),
    ]
