# Generated by Django 6.0.7 on 2026-07-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_dashboard_layout'),
        ('chiron', '0003_chironsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts_json', models.JSONField(default=dict)),
                ('narrative_text', models.TextField(blank=True, default='')),
                ('narrative_is_fallback', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_recaps', to='accounts.coachprofile')),
            ],
            options={
                'unique_together': {('coach', 'client')},
            },
        ),
    ]
