# Generated by Django 6.0.7 on 2026-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_dashboard_layout'),
        ('chiron', '0004_athleterecap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleterecap',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='athleterecap',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='athleterecap',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='athleterecap',
            index=models.Index(fields=['coach', 'client', '-generated_at'], name='chiron_athl_coach_i_ec5e4d_idx'),
        ),
    ]
