# Generated by Django 6.0.7 on 2026-07-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_dashboard_layout'),
        ('chiron', '0005_alter_athleterecap_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRecapFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_code', models.CharField(max_length=64)),
                ('useful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recap_feedback', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recap_feedback_given', to='accounts.coachprofile')),
                ('recap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chiron.athleterecap')),
            ],
            options={
                'unique_together': {('coach', 'client', 'recap', 'insight_code')},
            },
        ),
    ]
