# Generated by Django 6.0.7 on 2026-07-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_dashboard_layout'),
        ('chiron', '0006_athleterecapfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRecapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recap_settings', to='accounts.coachprofile')),
            ],
        ),
    ]
