# Generated by Django 6.0.4 on 2026-05-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('CONFIRMED', 'Iscritto'), ('UNSUBSCRIBED', 'Disiscritto')], default='PENDING', max_length=16)),
                ('confirm_token', models.CharField(blank=True, default='', max_length=128)),
                ('unsubscribe_token', models.CharField(max_length=128, unique=True)),
                ('consent_version', models.CharField(max_length=64)),
                ('consent_text_snapshot', models.TextField()),
                ('subscribed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('subscribed_user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='newsletter.subscriber')),
            ],
        ),
    ]
