# Generated by Django 6.0.4 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrelationship',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Full (Coach)'), ('WORKOUT', 'Workout only'), ('NUTRITION', 'Nutrition only')], max_length=20, null=True),
        ),
    ]
