# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('coaching', '0002_alter_coachingrelationship_relationship_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coachingrelationship',
            index=models.Index(fields=['coach', 'status'], name='coaching_co_coach_i_c02c65_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingrelationship',
            index=models.Index(fields=['client', 'status'], name='coaching_co_client__e2d199_idx'),
        ),
    ]
