# Generated by Django 6.0.4 on 2026-06-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_devicetoken'),
        ('coaching', '0003_coachingrelationship_coaching_co_coach_i_c02c65_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('duration_value', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('WEEKS', 'Settimane'), ('MONTHS', 'Mesi')], default='WEEKS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_phases', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_phases', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['coach', 'client'], name='coaching_co_coach_i_518db0_idx')],
            },
        ),
    ]
