# Generated by Django 6.0.4 on 2026-06-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_deprecated_client_fields'),
        ('coaching', '0004_coachingphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='bronze', max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_labels', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('coach', 'name')},
            },
        ),
        migrations.AddField(
            model_name='coachingrelationship',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='relationships', to='coaching.clientlabel'),
        ),
    ]
