"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,athlynk-production.up.railway.app', cast=Csv())

SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')
CONSENT_VERSION = config('CONSENT_VERSION', default='2026-06-11.v1')

# --- Analytics / PostHog / churn-prediction ---------------------------------
# Behavioural analytics + the coach risk dashboard. Everything degrades to a
# safe no-op when the keys are unset, so this ships dark until configured.
#   ANALYTICS_ENVIRONMENT  development | staging | production (tags every row/event)
#   POSTHOG_KEY            project write key; empty -> client + server capture off
#   POSTHOG_HOST          EU cloud by default
#   POSTHOG_PERSONAL_API_KEY  read key for HogQL feature enrichment; empty -> DB proxies
#   ANALYTICS_SLA_MINUTES  coach first-response SLA (rule engine + KPI), default 24h
#   TEST_ACCOUNT_EMAILS / INTERNAL_EMAIL_DOMAINS  governance allowlists
ANALYTICS_ENVIRONMENT = config('ANALYTICS_ENVIRONMENT', default='development')
POSTHOG_KEY = config('POSTHOG_KEY', default='')
POSTHOG_HOST = config('POSTHOG_HOST', default='https://eu.i.posthog.com')
POSTHOG_PERSONAL_API_KEY = config('POSTHOG_PERSONAL_API_KEY', default='')
POSTHOG_PROJECT_ID = config('POSTHOG_PROJECT_ID', default='')
ANALYTICS_SLA_MINUTES = config('ANALYTICS_SLA_MINUTES', default=1440, cast=int)
ANALYTICS_APP_VERSION = config('ANALYTICS_APP_VERSION', default='web')
TEST_ACCOUNT_EMAILS = config('TEST_ACCOUNT_EMAILS', default='', cast=Csv())
INTERNAL_EMAIL_DOMAINS = config('INTERNAL_EMAIL_DOMAINS', default='', cast=Csv())
# Where trained model artifacts live (gitignored).
ANALYTICS_MODELS_DIR = BASE_DIR / 'analytics_models'

# --- Apple Push Notifications (APNs) ----------------------------------------
# All optional. When the auth key / IDs are unset, push delivery is a silent
# no-op (see config.services.push) so the app runs untouched until the real
# Apple credentials are dropped in. To activate later, set these in the env:
#   APNS_AUTH_KEY (raw .p8 contents) or APNS_AUTH_KEY_PATH (file path),
#   APNS_KEY_ID, APNS_TEAM_ID, APNS_BUNDLE_ID, APNS_USE_SANDBOX.
APNS_AUTH_KEY = config('APNS_AUTH_KEY', default='')
APNS_AUTH_KEY_PATH = config('APNS_AUTH_KEY_PATH', default='')
APNS_KEY_ID = config('APNS_KEY_ID', default='')
APNS_TEAM_ID = config('APNS_TEAM_ID', default='')
APNS_BUNDLE_ID = config('APNS_BUNDLE_ID', default='com.athlynk.app')
APNS_USE_SANDBOX = config('APNS_USE_SANDBOX', default=True, cast=bool)

# --- Email configuration ---------------------------------------------------
# EMAIL_MODE selects the backend. Values:
#   console          -> stdout (default in dev)
#   file             -> writes to tmp/emails/
#   smtp_test        -> real SMTP with a personal test inbox (Gmail/Outlook)
#   smtp_production  -> real SMTP with provider/domain credentials
EMAIL_MODE = config('EMAIL_MODE', default='console')

if EMAIL_MODE == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL_MODE == 'file':
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR.parent / 'tmp' / 'emails'
else:  # smtp_test or smtp_production
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@localhost')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # App di Dominio
    'domain.accounts',
    'domain.coaching',
    'domain.workouts',
    'domain.nutrition',
    'domain.checks',
    'domain.calendar',
    'domain.billing',
    'domain.chat',
    'domain.newsletter',
    'domain.consent',
    'domain.chiron',
    'domain.analytics',
    'domain.shared',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.SessionSecurityMiddleware',
    'config.middleware.SanitizationMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.identity_context',
                'config.context_processors.posthog',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_DATABASE_URL = config('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(
        _DATABASE_URL,
        conn_max_age=0,
        # sslmode è un'opzione solo Postgres: con un DATABASE_URL sqlite locale
        # va omessa o la connessione fallisce.
        ssl_require=_DATABASE_URL.startswith('postgres'),
    )
}

# Supabase transaction pooler (porta 6543): multiplexa le connessioni a fine
# transazione. Con psycopg3 vanno disabilitati i prepared statement server-side
# (la connessione fisica cambia tra query → "prepared statement does not exist")
# e i server-side cursor (named cursor assumono connessione stabile).
if 'test' not in sys.argv and 'postgresql' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {'prepare_threshold': None}
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

# Il test runner crea/distrugge un DB dedicato a ogni esecuzione: su Supabase
# sarebbe lento e consumerebbe il free tier. I test girano quindi su SQLite locale.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_test.sqlite3',
    }


# Cache — used for rate limiting and short-lived counters.
# DatabaseCache persists across worker restarts and is multi-worker safe.
# Run `python manage.py createcachetable` once after deploying.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# Number of trusted reverse proxies in front of this app. Set to >0 in production
# (e.g. 1 behind a single Railway/Fly/Cloudflare hop) so client_ip() honors
# X-Forwarded-For. Keep at 0 in dev/single-host setups — otherwise attackers can
# spoof the header and bypass IP-based rate limiting.
TRUSTED_PROXY_COUNT = 0


# Request body / upload limits. Hard caps to block DoS via giant uploads or
# field-floods. Per-view code may impose tighter limits via services.sanitize.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024       # 10 MB form bodies (rare; mostly photos)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024       # 10 MB streamed to disk past this
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200                  # cap form-field flood
DATA_UPLOAD_MAX_NUMBER_FILES = 20                    # cap multi-file uploads

# Per-input-class caps used by sanitize helpers (in MB). Views opt in.
SANITIZE_LIMITS = {
    'image_mb': 10,
    'json_body_mb': 1,
    'short_text_chars': 200,
    'long_text_chars': 5000,
    'email_chars': 254,
}
SANITIZE_ALLOWED_IMAGE_MIMES = ('image/jpeg', 'image/png', 'image/webp')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# --- Media storage backend --------------------------------------------------
# Local dev: filesystem (media/). Production: Supabase Storage (S3-compatible),
# enabled only when SUPABASE_S3_ENDPOINT is set, so local runs stay on disk and
# untouched. Every upload site already writes through default_storage / model
# FileFields, so flipping the backend here routes all uploads to Supabase with
# no view changes. Bucket is PRIVATE — progress/body photos are sensitive — and
# .url() returns short-lived signed URLs (querystring_auth).
SUPABASE_S3_ENDPOINT = config('SUPABASE_S3_ENDPOINT', default='')

if SUPABASE_S3_ENDPOINT:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'endpoint_url': SUPABASE_S3_ENDPOINT,
                'access_key': config('SUPABASE_S3_ACCESS_KEY'),
                'secret_key': config('SUPABASE_S3_SECRET_KEY'),
                'bucket_name': config('SUPABASE_S3_BUCKET', default='media'),
                'region_name': config('SUPABASE_S3_REGION', default='eu-central-1'),
                'addressing_style': 'path',     # Supabase requires path-style URLs
                'signature_version': 's3v4',
                'querystring_auth': True,        # private bucket -> signed URLs
                'querystring_expire': 3600,      # 1h signed-URL lifetime
                'file_overwrite': False,         # never clobber an existing key
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# --- Web session security ---------------------------------------------------
# Browser sessions are short-lived and *sliding*: 30 minutes of inactivity logs
# the user out. SESSION_SAVE_EVERY_REQUEST renews the cookie on every request,
# so an actively-working user is never interrupted, while a forgotten tab is
# reaped quickly. SESSION_ABSOLUTE_TIMEOUT (enforced in
# config.middleware.SessionSecurityMiddleware) caps total lifetime regardless of
# activity, and login rotates the session key to defeat fixation.
#
# The iOS apps authenticate with signed Bearer tokens (see config/api.py),
# never the session cookie, so none of this touches them — athletes and coaches
# stay logged in on mobile until they sign out.
SESSION_COOKIE_AGE = 30 * 60                  # 30 min idle timeout
SESSION_SAVE_EVERY_REQUEST = True             # sliding window: renew on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True                # JS can never read the cookie
SESSION_COOKIE_SAMESITE = 'Lax'              # blocks cross-site cookie sends
SESSION_ABSOLUTE_TIMEOUT = 7 * 24 * 60 * 60   # 7-day hard ceiling per login


# --- Production transport security -----------------------------------------
# Only enforced when DEBUG is off, so local http://127.0.0.1 development (and
# the iOS app talking to http://localhost) keeps working untouched. In
# production every response is HTTPS-only with HSTS, and the session/CSRF
# cookies are marked Secure so they never travel in plaintext.
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # handled by Railway/Fly/Cloudflare TLS termination
    SECURE_HSTS_SECONDS = 31536000              # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Behind a TLS-terminating proxy (Railway/Fly/Cloudflare), trust its scheme
    # header so SECURE_SSL_REDIRECT doesn't loop. Only honored alongside a
    # configured TRUSTED_PROXY_COUNT > 0.
    if TRUSTED_PROXY_COUNT > 0:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Hosts allowed to submit CSRF-protected forms (full https origins).
    CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

