"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,athlynk-production.up.railway.app,app.athlynk.it', cast=Csv())

# Force-trust our own hosts even when an explicit ALLOWED_HOSTS env var is set
# (a stale value that omits the current domain would otherwise raise
# DisallowedHost -> 400 Bad Request). Railway injects RAILWAY_PUBLIC_DOMAIN at
# runtime; trust it too so the service host is never rejected after a rename.
RAILWAY_PUBLIC_DOMAIN = config('RAILWAY_PUBLIC_DOMAIN', default='')
for _host in ('app.athlynk.it', 'athlynk-production.up.railway.app', RAILWAY_PUBLIC_DOMAIN):
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')
# Guard: in production the localhost default would bake 127.0.0.1 links into
# every email (verify, reset, unsubscribe). Fail at boot instead of silently
# sending dead links — set SITE_URL=https://app.athlynk.it on the host.
if not DEBUG and ('127.0.0.1' in SITE_URL or 'localhost' in SITE_URL):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'SITE_URL must be set to the public URL in production '
        f'(got {SITE_URL!r}). Set SITE_URL=https://app.athlynk.it.'
    )
CONSENT_VERSION = config('CONSENT_VERSION', default='2026-06-11.v1')

# --- Analytics / PostHog / churn-prediction ---------------------------------
# Behavioural analytics + the coach risk dashboard. Everything degrades to a
# safe no-op when the keys are unset, so this ships dark until configured.
#   ANALYTICS_ENVIRONMENT  development | staging | production (tags every row/event)
#   POSTHOG_KEY            project write key; empty -> client + server capture off
#   POSTHOG_HOST          EU cloud by default
#   POSTHOG_PERSONAL_API_KEY  read key for HogQL feature enrichment; empty -> DB proxies
#   ANALYTICS_SLA_MINUTES  coach first-response SLA (rule engine + KPI), default 24h
#   TEST_ACCOUNT_EMAILS / INTERNAL_EMAIL_DOMAINS  governance allowlists
ANALYTICS_ENVIRONMENT = config('ANALYTICS_ENVIRONMENT', default='development')
POSTHOG_KEY = config('POSTHOG_KEY', default='')
POSTHOG_HOST = config('POSTHOG_HOST', default='https://eu.i.posthog.com')
POSTHOG_PERSONAL_API_KEY = config('POSTHOG_PERSONAL_API_KEY', default='')
POSTHOG_PROJECT_ID = config('POSTHOG_PROJECT_ID', default='')
ANALYTICS_SLA_MINUTES = config('ANALYTICS_SLA_MINUTES', default=1440, cast=int)
ANALYTICS_APP_VERSION = config('ANALYTICS_APP_VERSION', default='web')
TEST_ACCOUNT_EMAILS = config('TEST_ACCOUNT_EMAILS', default='', cast=Csv())
INTERNAL_EMAIL_DOMAINS = config('INTERNAL_EMAIL_DOMAINS', default='', cast=Csv())
# Where trained model artifacts live (gitignored).
ANALYTICS_MODELS_DIR = BASE_DIR / 'analytics_models'

# --- Apple Push Notifications (APNs) ----------------------------------------
# All optional. When the auth key / IDs are unset, push delivery is a silent
# no-op (see config.services.push) so the app runs untouched until the real
# Apple credentials are dropped in. To activate later, set these in the env:
#   APNS_AUTH_KEY (raw .p8 contents) or APNS_AUTH_KEY_PATH (file path),
#   APNS_KEY_ID, APNS_TEAM_ID, APNS_BUNDLE_ID, APNS_USE_SANDBOX.
APNS_AUTH_KEY = config('APNS_AUTH_KEY', default='')
APNS_AUTH_KEY_PATH = config('APNS_AUTH_KEY_PATH', default='')
APNS_KEY_ID = config('APNS_KEY_ID', default='')
APNS_TEAM_ID = config('APNS_TEAM_ID', default='')
APNS_BUNDLE_ID = config('APNS_BUNDLE_ID', default='com.athlynk.app')
APNS_USE_SANDBOX = config('APNS_USE_SANDBOX', default=True, cast=bool)

# --- Email configuration ---------------------------------------------------
# EMAIL_MODE selects the backend. Values:
#   console          -> stdout (default in dev)
#   file             -> writes to tmp/emails/
#   resend           -> Resend SMTP relay, auth via RESEND_API_KEY (production)
#   smtp_test        -> real SMTP with a personal test inbox (Gmail/Outlook)
#   smtp_production  -> real SMTP with provider/domain credentials
# Normalize: a stray space/case in the Railway env var must not silently fall
# through to the smtp.gmail.com default branch (which has no credentials).
EMAIL_MODE = config('EMAIL_MODE', default='console').strip().lower()

if EMAIL_MODE == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL_MODE == 'file':
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR.parent / 'tmp' / 'emails'
elif EMAIL_MODE == 'resend':
    # Resend HTTP API (not SMTP). Cloud hosts (Render/Railway/Fly) block outbound
    # SMTP ports, so smtp.resend.com:587 times out at TCP connect. The API on :443
    # is never blocked. Auth via RESEND_API_KEY; the sending domain
    # (app.athlynk.it) must be verified in Resend.
    EMAIL_BACKEND = 'config.services.email_backend.ResendAPIBackend'
    RESEND_API_KEY = config('RESEND_API_KEY', default='').strip()
else:  # smtp_test or smtp_production
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Cap the SMTP socket. Without this, EMAIL_TIMEOUT defaults to None (block
# forever): a hung connection to the SMTP host keeps the request open past
# gunicorn's worker timeout, the worker is SIGKILLed mid-send (before the
# try/except in services/email.py can catch/log it), and the client gets a
# bare 500. With a timeout the send fails fast, gets logged, and degrades
# gracefully instead of 500ing.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@localhost')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)


# --- Stripe / Payments -----------------------------------------------------
# Platform purchase (coach pays Athlynk) started from the static marketing site
# and fulfilled via webhook. Keys live in the env, empty by default so the app
# boots without Stripe configured (the checkout view degrades gracefully).
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
# Recurring (monthly) price IDs, one per plan, plus the Chiron add-on. Empty by
# default; a plan whose price ID is unset is treated as unavailable at checkout.
STRIPE_PRICE_ATHENA = config('STRIPE_PRICE_ATHENA', default='')
STRIPE_PRICE_APOLLO = config('STRIPE_PRICE_APOLLO', default='')
STRIPE_PRICE_ZEUS = config('STRIPE_PRICE_ZEUS', default='')
STRIPE_PRICE_CHIRON = config('STRIPE_PRICE_CHIRON', default='')
# Public marketing site (Vercel) — Stripe success/cancel redirects land here.
WEBSITE_URL = config('WEBSITE_URL', default='https://athlynk.it')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    
    # App di Dominio
    'domain.accounts',
    'domain.coaching',
    'domain.workouts',
    'domain.nutrition',
    'domain.checks',
    'domain.calendar',
    'domain.billing',
    'domain.chat',
    'domain.newsletter',
    'domain.consent',
    'domain.chiron',
    'domain.analytics',
    'domain.shared',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.SessionSecurityMiddleware',
    'config.middleware.GlobalRateLimitMiddleware',
    'config.middleware.SanitizationMiddleware',
    'config.middleware.ClientAccessMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.identity_context',
                'config.context_processors.posthog',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_DATABASE_URL = config('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(
        _DATABASE_URL,
        conn_max_age=0,
        # sslmode è un'opzione solo Postgres: con un DATABASE_URL sqlite locale
        # va omessa o la connessione fallisce.
        ssl_require=_DATABASE_URL.startswith('postgres'),
    )
}

# Supabase transaction pooler (porta 6543): multiplexa le connessioni a fine
# transazione. Con psycopg3 vanno disabilitati i prepared statement server-side
# (la connessione fisica cambia tra query → "prepared statement does not exist")
# e i server-side cursor (named cursor assumono connessione stabile).
if 'test' not in sys.argv and 'postgresql' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {'prepare_threshold': None}
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

# Il test runner crea/distrugge un DB dedicato a ogni esecuzione: su Supabase
# sarebbe lento e consumerebbe il free tier. I test girano quindi su SQLite locale.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_test.sqlite3',
    }


# Cache — used for rate limiting and short-lived counters.
# LocMemCache = in-process memory, zero DB queries. Rate-limit counters are
# per-worker (not shared across gunicorn workers), which is acceptable given
# the generous limits. DatabaseCache caused 6-9 extra Supabase queries per
# API call, producing 20 s load times under concurrent tab usage.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Number of trusted reverse proxies in front of this app. Set to >0 in production
# (e.g. 1 behind a single Railway/Fly/Cloudflare hop) so client_ip() honors
# X-Forwarded-For. Keep at 0 in dev/single-host setups — otherwise attackers can
# spoof the header and bypass IP-based rate limiting.
TRUSTED_PROXY_COUNT = 0


# Request body / upload limits. Hard caps to block DoS via giant uploads or
# field-floods. Per-view code may impose tighter limits via services.sanitize.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024       # 10 MB form bodies (rare; mostly photos)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024       # 10 MB streamed to disk past this
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200                  # cap form-field flood
DATA_UPLOAD_MAX_NUMBER_FILES = 20                    # cap multi-file uploads

# Per-input-class caps used by sanitize helpers (in MB). Views opt in.
SANITIZE_LIMITS = {
    'image_mb': 10,
    'video_mb': 100,
    'json_body_mb': 1,
    'short_text_chars': 200,
    'long_text_chars': 5000,
    'email_chars': 254,
    # Per-string cap applied by the blanket sanitize.clean_payload pass on every
    # JSON API body. Generous so it acts as a DoS safety net, not a field
    # validator — tighter per-field caps stay the model/view's job.
    'payload_text_chars': 20000,
}

# Per-request API rate limits (fixed window, cache-backed via services.ratelimit).
# Enforced inside the api_view / coach_dual_auth decorators, so every mobile and
# dual-auth endpoint is covered. Reads = GET/HEAD; writes = POST/PUT/PATCH/DELETE.
# A parallel per-IP bucket runs at `ip_multiplier`x the per-user cap so a single
# host can't bypass the per-user limit by minting many tokens. `builder_per_min`
# is a separate, looser bucket for coach_dual_auth (web plan builders autosave on
# a 1.5s debounce, so they need headroom a 30/min write cap wouldn't give).
# Raise any value if legitimate clients hit 429.
API_RATE_LIMITS = {
    'read_per_min': 120,
    'write_per_min': 30,
    'builder_per_min': 120,
    'ip_multiplier': 2,
    'window_seconds': 60,
}
SANITIZE_ALLOWED_IMAGE_MIMES = ('image/jpeg', 'image/png', 'image/webp')

# Blanket per-IP request cap applied to every endpoint by
# config.middleware.GlobalRateLimitMiddleware — a backstop for views without
# their own limiter. Generous so normal coach/athlete usage never trips it;
# raise per_min if legitimate clients hit 429. Disabled under the test runner so
# request-heavy test cases stay deterministic. Set per_min to 0 to disable.
GLOBAL_RATE_LIMIT = {
    'per_min': 0 if 'test' in sys.argv else 300,
    'window_seconds': 60,
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# --- Media storage backend --------------------------------------------------
# Local dev: filesystem (media/). Production: Supabase Storage (S3-compatible),
# enabled only when SUPABASE_S3_ENDPOINT is set, so local runs stay on disk and
# untouched. Every upload site already writes through default_storage / model
# FileFields, so flipping the backend here routes all uploads to Supabase with
# no view changes. Bucket is PRIVATE — progress/body photos are sensitive — and
# .url() returns short-lived signed URLs (querystring_auth).
SUPABASE_S3_ENDPOINT = config('SUPABASE_S3_ENDPOINT', default='')

if SUPABASE_S3_ENDPOINT:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'endpoint_url': SUPABASE_S3_ENDPOINT,
                'access_key': config('SUPABASE_S3_ACCESS_KEY'),
                'secret_key': config('SUPABASE_S3_SECRET_KEY'),
                'bucket_name': config('SUPABASE_S3_BUCKET', default='media'),
                'region_name': config('SUPABASE_S3_REGION', default='eu-central-1'),
                'addressing_style': 'path',     # Supabase requires path-style URLs
                'signature_version': 's3v4',
                'querystring_auth': True,        # private bucket -> signed URLs
                'querystring_expire': 3600,      # 1h signed-URL lifetime
                'file_overwrite': False,         # never clobber an existing key
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# --- Web session security ---------------------------------------------------
# Browser sessions are short-lived and *sliding*: 30 minutes of inactivity logs
# the user out. SESSION_SAVE_EVERY_REQUEST renews the cookie on every request,
# so an actively-working user is never interrupted, while a forgotten tab is
# reaped quickly. SESSION_ABSOLUTE_TIMEOUT (enforced in
# config.middleware.SessionSecurityMiddleware) caps total lifetime regardless of
# activity, and login rotates the session key to defeat fixation.
#
# The iOS apps authenticate with signed Bearer tokens (see config/api.py),
# never the session cookie, so none of this touches them — athletes and coaches
# stay logged in on mobile until they sign out.
SESSION_COOKIE_AGE = 30 * 60                  # 30 min idle timeout
SESSION_SAVE_EVERY_REQUEST = True             # sliding window: renew on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True                # JS can never read the cookie
SESSION_COOKIE_SAMESITE = 'Lax'              # blocks cross-site cookie sends
SESSION_ABSOLUTE_TIMEOUT = 7 * 24 * 60 * 60   # 7-day hard ceiling per login


# --- Production transport security -----------------------------------------
# Only enforced when DEBUG is off, so local http://127.0.0.1 development (and
# the iOS app talking to http://localhost) keeps working untouched. In
# production every response is HTTPS-only with HSTS, and the session/CSRF
# cookies are marked Secure so they never travel in plaintext.
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # handled by Railway/Fly/Cloudflare TLS termination
    SECURE_HSTS_SECONDS = 31536000              # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Behind a TLS-terminating proxy (Railway/Fly/Cloudflare), trust its scheme
    # header so SECURE_SSL_REDIRECT doesn't loop. Only honored alongside a
    # configured TRUSTED_PROXY_COUNT > 0.
    if TRUSTED_PROXY_COUNT > 0:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Hosts allowed to submit CSRF-protected forms (full https origins).
    CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://app.athlynk.it,https://athlynk-production.up.railway.app',
    cast=Csv()
)
    # Mirror the ALLOWED_HOSTS hardening: guarantee our own origins are trusted
    # for CSRF even if an explicit env var omits them, so login POSTs don't 403.
    for _origin in (
        'https://app.athlynk.it',
        'https://athlynk-production.up.railway.app',
        f'https://{RAILWAY_PUBLIC_DOMAIN}' if RAILWAY_PUBLIC_DOMAIN else '',
    ):
        if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# CORS — restrict cross-origin browser access to /api/* only.
# Native iOS clients are unaffected (no browser CORS applies to URLSession).
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in config('CORS_ALLOWED_ORIGINS', default='https://app.athlynk.it').split(',')
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = False


# --- Logging -----------------------------------------------------------------
# Without this, Django's default config routes unhandled 500 tracebacks to
# mail_admins only (never configured) and nothing is printed, so production
# 500s are invisible in the Railway deploy logs. Send everything to stderr.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Unhandled view exceptions (the 500 tracebacks) land here.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# --- Sentry -------------------------------------------------------------
# No-op when SENTRY_DSN is unset (local dev). Set it in Railway env vars
# after creating the project on sentry.io.
#
# Env vars to set in Railway (Athlynk service):
#   SENTRY_DSN                  — project DSN from sentry.io (required to activate)
#   SENTRY_TRACES_SAMPLE_RATE   — fraction of requests traced   (default 0.10)
#   SENTRY_PROFILES_SAMPLE_RATE — fraction of traces profiled   (default 0.0)
import logging
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.openai import OpenAIIntegration
from sentry_sdk.integrations.langchain import LangchainIntegration

sentry_sdk.init(
    dsn=config('SENTRY_DSN', default=''),
    integrations=[
        DjangoIntegration(
            transaction_style='url',    # group by URL pattern, not full path
            middleware_spans=True,
            signals_spans=False,
            cache_spans=True,
        ),
        LoggingIntegration(
            level=logging.INFO,         # breadcrumbs from INFO+
            event_level=logging.ERROR,  # Sentry events only for ERROR+
        ),
        OpenAIIntegration(
            include_prompts=False,      # never send prompt content to Sentry (GDPR)
        ),
        LangchainIntegration(
            include_prompts=False,
        ),
    ],
    traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.10, cast=float),
    profiles_sample_rate=config('SENTRY_PROFILES_SAMPLE_RATE', default=0.0, cast=float),
    send_default_pii=False,   # no IP / email in events (GDPR)
    environment=config('RAILWAY_ENVIRONMENT', default='development'),
    release=config('RAILWAY_GIT_COMMIT_SHA', default=''),
)


