# Generated by Django 6.0.4 on 2026-06-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_user_is_internal_user_user_is_test_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('churn_30d', 'churn_30d'), ('renewal_7d', 'renewal_7d'), ('risk_class', 'risk_class')], max_length=20)),
                ('version', models.CharField(max_length=80, unique=True)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('n_train', models.IntegerField(default=0)),
                ('n_valid', models.IntegerField(default=0)),
                ('is_bootstrap', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'is_active'], name='analytics_m_target_07cb57_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_type', models.CharField(max_length=60)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(blank=True, default='SENT', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', '-created_at'], name='analytics_a_coach_i_3dcf18_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoachBusinessMetricsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('active_clients_count', models.IntegerField(default=0)),
                ('renewals_due_7d', models.IntegerField(default=0)),
                ('renewals_completed_30d', models.IntegerField(default=0)),
                ('churn_rate_30d', models.FloatField(default=0.0)),
                ('avg_first_response_minutes', models.FloatField(blank=True, null=True)),
                ('sla_adherence_rate', models.FloatField(default=0.0)),
                ('backlog_open_reviews', models.IntegerField(default=0)),
                ('payment_failure_rate', models.FloatField(default=0.0)),
                ('at_risk_clients_count', models.IntegerField(default=0)),
                ('avg_risk_score', models.FloatField(default=0.0)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_per_active_client', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('environment', models.CharField(default='development', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', '-snapshot_date'], name='analytics_c_coach_i_718242_idx')],
                'unique_together': {('coach', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyFeatureStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('days_since_last_login', models.IntegerField(blank=True, null=True)),
                ('login_count_7d', models.IntegerField(default=0)),
                ('login_count_30d', models.IntegerField(default=0)),
                ('days_since_last_checkin', models.IntegerField(blank=True, null=True)),
                ('checkins_completed_7d', models.IntegerField(default=0)),
                ('checkins_missed_30d', models.IntegerField(default=0)),
                ('messages_7d', models.IntegerField(default=0)),
                ('ignored_reminders_30d', models.IntegerField(default=0)),
                ('feature_usage_count_7d', models.IntegerField(default=0)),
                ('plan_updates_30d', models.IntegerField(default=0)),
                ('engagement_delta_7d_vs_30d', models.FloatField(blank=True, null=True)),
                ('avg_coach_response_minutes_30d', models.FloatField(blank=True, null=True)),
                ('avg_review_duration_seconds_30d', models.FloatField(blank=True, null=True)),
                ('days_to_renewal', models.IntegerField(blank=True, null=True)),
                ('payment_failures_30d', models.IntegerField(default=0)),
                ('relationship_age_days', models.IntegerField(blank=True, null=True)),
                ('active_package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_internal_user', models.BooleanField(default=False)),
                ('is_test_account', models.BooleanField(default=False)),
                ('environment', models.CharField(default='development', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_rows', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feature_rows', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'snapshot_date'], name='analytics_d_coach_i_1e6dc1_idx'), models.Index(fields=['snapshot_date', 'environment'], name='analytics_d_snapsho_7ea8a2_idx')],
                'unique_together': {('client', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='LeadPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('stage', models.CharField(choices=[('NEW', 'Nuovo'), ('CONTACTED', 'Contattato'), ('QUALIFIED', 'Qualificato'), ('WON', 'Acquisito'), ('LOST', 'Perso')], default='NEW', max_length=20)),
                ('value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'stage'], name='analytics_l_coach_i_d82baa_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('risk_score_rule_based', models.IntegerField(default=0)),
                ('risk_probability_ml', models.FloatField(blank=True, null=True)),
                ('risk_class', models.CharField(choices=[('low', 'Basso'), ('medium', 'Medio'), ('high', 'Alto')], default='low', max_length=10)),
                ('top_reason_codes', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=80)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('is_internal_user', models.BooleanField(default=False)),
                ('is_test_account', models.BooleanField(default=False)),
                ('environment', models.CharField(default='development', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_risk_scores', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'snapshot_date', 'risk_class'], name='analytics_r_coach_i_c5ad58_idx'), models.Index(fields=['snapshot_date', 'risk_class'], name='analytics_r_snapsho_d54059_idx')],
                'unique_together': {('client', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Aperto'), ('COMPLETED', 'Completato')], default='OPEN', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_tasks', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'status'], name='analytics_t_coach_i_0da28f_idx'), models.Index(fields=['client', 'status'], name='analytics_t_client__78986f_idx')],
            },
        ),
    ]
