# Generated by Django 6.0.4 on 2026-05-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_food_italian_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='raw_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Lunedì'), ('TUESDAY', 'Martedì'), ('WEDNESDAY', 'Mercoledì'), ('THURSDAY', 'Giovedì'), ('FRIDAY', 'Venerdì'), ('SATURDAY', 'Sabato'), ('SUNDAY', 'Domenica')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='nutrition.nutritionplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietday'),
        ),
    ]
