# Generated by Django 6.0.4 on 2026-05-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_nutritionplan_kind_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='include_substitutions_in_avg',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MealItemSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ISOKCAL', 'Isocalorica'), ('ISOPROT', 'Isoproteica'), ('ISOCARB', 'Isoglucidica')], max_length=10)),
                ('quantity_g', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='nutrition.mealitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
