# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('nutrition', '0008_nutritionplan_include_substitutions_in_avg_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nutritionassignment',
            index=models.Index(fields=['client', 'coach', 'status'], name='nutrition_n_client__f1650b_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionassignment',
            index=models.Index(fields=['coach', '-assigned_at'], name='nutrition_n_coach_i_81d8a0_idx'),
        ),
    ]
