# Generated by Django 6.0.4 on 2026-05-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_nutritionassignment_nutrition_n_client__f1650b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietday',
            name='target_carb_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietday',
            name='target_fat_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietday',
            name='target_kcal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietday',
            name='target_protein_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='plan_mode',
            field=models.CharField(choices=[('FOOD', 'Alimenti'), ('MACRO', 'Macronutrienti')], default='FOOD', max_length=10),
        ),
        migrations.CreateModel(
            name='ClientMacroLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('MONDAY', 'Lunedì'), ('TUESDAY', 'Martedì'), ('WEDNESDAY', 'Mercoledì'), ('THURSDAY', 'Giovedì'), ('FRIDAY', 'Venerdì'), ('SATURDAY', 'Sabato'), ('SUNDAY', 'Domenica')], max_length=10, null=True)),
                ('raw_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_g', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_log', to='nutrition.nutritionassignment')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['assignment', 'day_of_week'], name='nutrition_c_assignm_30cbf9_idx')],
            },
        ),
    ]
