# Generated by Django 6.0.4 on 2026-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_clientmacrolog_meal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-genericity_score', 'nome_alimento']},
        ),
        migrations.AddField(
            model_name='food',
            name='genericity_score',
            field=models.FloatField(db_column='Genericity_Score', db_index=True, default=0.0),
        ),
    ]
