# Generated by Django 6.0.4 on 2026-06-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_deprecated_client_fields'),
        ('nutrition', '0013_alter_food_options_food_genericity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementsheetitem',
            name='supplement',
        ),
        migrations.RemoveField(
            model_name='supplementassignment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='supplementassignment',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='supplementassignment',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='supplementsheet',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='supplementsheetitem',
            name='sheet',
        ),
        migrations.CreateModel(
            name='SupplementProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_protocols', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('cps', 'cps')], default='g', max_length=10)),
                ('timing', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.supplementprotocol')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='supplement_sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_plan', to='nutrition.supplementprotocol'),
        ),
        migrations.CreateModel(
            name='SupplementProtocolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_assignments', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_assignments_given', to='accounts.coachprofile')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nutrition.supplementprotocol')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('cps', 'cps')], default='g', max_length=10)),
                ('timing', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_template_items', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Supplement',
        ),
        migrations.DeleteModel(
            name='SupplementAssignment',
        ),
        migrations.DeleteModel(
            name='SupplementSheetItem',
        ),
        migrations.DeleteModel(
            name='SupplementSheet',
        ),
    ]
