# Generated by Django 6.0.4 on 2026-07-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_remove_supplementsheetitem_supplement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplementTemplateItem',
        ),
    ]
