# Generated by Django 6.0.4 on 2026-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_terms_accepted_at_user_terms_version'),
        ('nutrition', '0015_delete_supplementtemplateitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nutritionplan',
            index=models.Index(fields=['coach', 'status'], name='nutrition_n_coach_i_7b3fee_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionplan',
            index=models.Index(fields=['coach', 'is_template'], name='nutrition_n_coach_i_6f9ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplementprotocolassignment',
            index=models.Index(fields=['coach', 'status'], name='nutrition_s_coach_i_2ae9cf_idx'),
        ),
    ]
