# Generated by Django 6.0.4 on 2026-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_nutritionplan_nutrition_n_coach_i_7b3fee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionassignment',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('WEEKS', 'settimane'), ('MONTHS', 'mesi')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritionassignment',
            name='duration_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
