"""
System preset templates for check-in questionnaires.

Each coach receives a personal clone of these presets the first time they
open `Gestisci Modelli`. Coaches can modify their copies; the `Ripristina`
action re-reads the original definition from this module.

Schema:
    PRESETS[key] = {
        'title':       str,
        'description': str,
        'steps':       [{'id': str, 'label': str, 'icon': str}, ...],
        'questions':   [{
            'id': str, 'step_id': str, 'type': str, 'label': str,
            'required': bool, 'report_visible': bool,
            # type-specific keys: 'unit', 'min', 'max', 'minLabel', 'maxLabel', 'options', 'placeholder'
        }, ...],
    }

Supported question types: antropometria, metrica, media, si_no, radio, checkbox, aperta, allegato.
The `antropometria` type bundles peso/circonferenze/pliche (see domain.checks.anthropometry);
its config keys are: 'weight' (bool), 'circumferences' (ordered stored-keys),
'skinfolds' (ordered keys).
"""

PRESETS = {
    # ──────────────────────────────────────────────────────────────────
    'prima_valutazione': {
        'title': 'Prima valutazione',
        'description': 'Anamnesi iniziale completa: storia personale e clinica, antropometria, allenamento, esame fisico nutrizionale, abitudini alimentari, storico diete, obiettivi e calcolo fabbisogni. I dati anagrafici (nome, data di nascita, età, sesso) sono già nella scheda atleta. Compila solo i campi utili: quelli non necessari si possono rimuovere in fase di compilazione.',
        'steps': [
            {'id': 's_storia',      'label': 'Storia personale', 'icon': 'ph-identification-card'},
            {'id': 's_antrop',      'label': 'Antropometria',    'icon': 'ph-ruler'},
            {'id': 's_allenamento', 'label': 'Allenamento',      'icon': 'ph-barbell'},
            {'id': 's_esame',       'label': 'Esame fisico',     'icon': 'ph-stethoscope'},
            {'id': 's_alimentare',  'label': 'Storia alimentare','icon': 'ph-fork-knife'},
            {'id': 's_diete',       'label': 'Diete precedenti', 'icon': 'ph-clock-counter-clockwise'},
            {'id': 's_obiettivi',   'label': 'Obiettivi',        'icon': 'ph-target'},
            {'id': 's_fabbisogni',  'label': 'Fabbisogni',       'icon': 'ph-calculator'},
        ],
        'questions': [
            # ── 1 · Storia personale ──────────────────────────────────
            {'id': 'pv_prof_seguito', 'step_id': 's_storia', 'type': 'checkbox',
             'label': 'Sei attualmente seguito/a da altri professionisti?',
             'options': ['Dietista', 'Medico sportivo', 'Psicologo', 'Fisioterapista', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_clin_patologie', 'step_id': 's_storia', 'type': 'aperta',
             'label': 'Patologie diagnosticate', 'placeholder': 'Diagnosi note, anno, stato attuale…',
             'required': False, 'report_visible': True},
            {'id': 'pv_clin_allergie', 'step_id': 's_storia', 'type': 'aperta',
             'label': 'Allergie note', 'placeholder': 'Alimentari, farmacologiche, ambientali…',
             'required': False, 'report_visible': True},
            {'id': 'pv_clin_interventi', 'step_id': 's_storia', 'type': 'aperta',
             'label': 'Interventi chirurgici rilevanti', 'placeholder': 'Tipo di intervento e anno…',
             'required': False, 'report_visible': True},
            {'id': 'pv_clin_familiarita', 'step_id': 's_storia', 'type': 'aperta',
             'label': 'Familiarità per patologie metaboliche o cardiovascolari',
             'placeholder': 'Diabete, ipertensione, dislipidemie, cardiopatie…',
             'required': False, 'report_visible': True},
            {'id': 'pv_clin_farmaci', 'step_id': 's_storia', 'type': 'aperta',
             'label': 'Farmaci assunti regolarmente', 'placeholder': 'Per ogni farmaco: nome · dose · motivo',
             'required': False, 'report_visible': True},

            # ── 2 · Misure antropometriche ────────────────────────────
            {'id': 'pv_antrop_altezza', 'step_id': 's_antrop', 'type': 'metrica',
             'label': 'Altezza', 'unit': 'cm', 'required': False, 'report_visible': True},
            {'id': 'antropometria', 'step_id': 's_antrop', 'type': 'antropometria',
             'label': 'Peso attuale e compartimenti corporei',
             'weight': True,
             'circumferences': ['head', 'neck', 'chest', 'arm_relaxed_l', 'arm_relaxed_r',
                                'arm_flexed_l', 'arm_flexed_r', 'forearm_l', 'forearm_r',
                                'wrist_l', 'wrist_r', 'waist', 'gluteal', 'thigh_l', 'thigh_r',
                                'calf_l', 'calf_r', 'ankle_l', 'ankle_r'],
             'skinfolds': ['biceps', 'triceps', 'subscapular', 'supraspinale', 'suprailiac',
                           'abdominal', 'front_thigh', 'medial_calf'],
             'required': False, 'report_visible': True},
            {'id': 'pv_antrop_peso_abituale', 'step_id': 's_antrop', 'type': 'metrica',
             'label': 'Peso abituale', 'unit': 'kg', 'required': False, 'report_visible': True},
            {'id': 'pv_antrop_peso_estremi', 'step_id': 's_antrop', 'type': 'aperta',
             'label': 'Peso più alto e più basso in età adulta',
             'placeholder': 'Es. minimo 70 kg · massimo 95 kg', 'required': False, 'report_visible': True},
            {'id': 'pv_antrop_var_peso', 'step_id': 's_antrop', 'type': 'si_no',
             'label': "Variazioni di peso importanti nell'ultimo anno?",
             'required': False, 'report_visible': True},
            {'id': 'pv_antrop_var_tipo', 'step_id': 's_antrop', 'type': 'radio',
             'label': 'Se sì: erano volontarie o involontarie?',
             'options': ['Volontarie', 'Involontarie', 'In parte entrambe'],
             'required': False, 'report_visible': True},
            {'id': 'pv_antrop_freq_pesata', 'step_id': 's_antrop', 'type': 'radio',
             'label': 'Con quale frequenza ti pesi?',
             'options': ['Mai', 'Mensile', 'Settimanale', 'Quotidiana', 'Più volte al giorno'],
             'required': False, 'report_visible': True},
            {'id': 'pv_antrop_note', 'step_id': 's_antrop', 'type': 'aperta',
             'label': 'Osservazioni antropometriche', 'placeholder': 'Note su postura, distribuzione, asimmetrie…',
             'required': False, 'report_visible': True},

            # ── 3 · Attività fisica e allenamento ─────────────────────
            {'id': 'pv_all_discipline', 'step_id': 's_allenamento', 'type': 'checkbox',
             'label': 'Disciplina/e praticata/e',
             'options': ['Bodybuilding', 'Powerlifting', 'Weightlifting', 'Strength training',
                         'Endurance', 'CrossFit / Functional', 'Sport di squadra', 'Sport misti', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_all_anni', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Da quanti anni ti alleni con continuità', 'unit': 'anni',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_sedute', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Sedute di allenamento a settimana', 'unit': 'n/sett',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_durata', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Durata media della seduta', 'unit': 'min',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_fase', 'step_id': 's_allenamento', 'type': 'radio',
             'label': 'Fase attuale del programma',
             'options': ['Ipertrofia', 'Forza', 'Definizione', 'Mantenimento', 'Preparazione gara', 'Recupero'],
             'required': False, 'report_visible': True},
            {'id': 'pv_all_cardio_sess', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Sessioni cardio strutturate a settimana', 'unit': 'sess/sett',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_cardio_durata', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Durata media sessione cardio', 'unit': 'min',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_attivita_quot', 'step_id': 's_allenamento', 'type': 'radio',
             'label': 'Livello di attività quotidiana', 'options': ['Bassa', 'Media', 'Alta'],
             'required': False, 'report_visible': True},
            {'id': 'pv_all_passi', 'step_id': 's_allenamento', 'type': 'metrica',
             'label': 'Passi medi giornalieri (se disponibili)', 'unit': 'passi/die',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_programmazione', 'step_id': 's_allenamento', 'type': 'radio',
             'label': 'Programmazione attuale',
             'options': ['Coach personale', 'Programma autonomo', 'Schema generico', 'Nessuna struttura'],
             'required': False, 'report_visible': True},
            {'id': 'pv_all_infortuni', 'step_id': 's_allenamento', 'type': 'aperta',
             'label': 'Infortuni o limitazioni fisiche', 'placeholder': 'Distretti coinvolti, da quando, limitazioni attuali…',
             'required': False, 'report_visible': True},
            {'id': 'pv_all_energia', 'step_id': 's_allenamento', 'type': 'media',
             'label': 'Energia e recupero percepiti', 'min': 1, 'max': 10,
             'minLabel': 'Scarsi', 'maxLabel': 'Ottimi', 'required': False, 'report_visible': True},
            {'id': 'pv_all_cali_perf', 'step_id': 's_allenamento', 'type': 'si_no',
             'label': 'Cali recenti di performance', 'required': False, 'report_visible': True},

            # ── 4 · Esame fisico basato sulla nutrizione ──────────────
            {'id': 'pv_reds_calorie', 'step_id': 's_esame', 'type': 'si_no',
             'label': 'Negli ultimi mesi hai ridotto volontariamente le calorie aumentando il carico di lavoro?',
             'required': False, 'report_visible': True},
            {'id': 'pv_reds_forza', 'step_id': 's_esame', 'type': 'si_no',
             'label': 'Cali di forza o performance senza causa apparente',
             'required': False, 'report_visible': True},
            {'id': 'pv_reds_freddo', 'step_id': 's_esame', 'type': 'si_no',
             'label': 'Sensazione di freddo frequente o estremità fredde',
             'required': False, 'report_visible': True},
            {'id': 'pv_reds_sonno', 'step_id': 's_esame', 'type': 'si_no',
             'label': 'Sonno disturbato o non ristoratore', 'required': False, 'report_visible': True},
            {'id': 'pv_reds_fratture', 'step_id': 's_esame', 'type': 'si_no',
             'label': 'Fratture da stress o dolori ossei ricorrenti',
             'required': False, 'report_visible': True},
            {'id': 'pv_gi_alvo', 'step_id': 's_esame', 'type': 'radio',
             'label': 'Alvo', 'options': ['Regolare', 'Stitichezza', 'Diarrea', 'Alternanza', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_gi_sintomi', 'step_id': 's_esame', 'type': 'checkbox',
             'label': 'Sintomi gastrointestinali presenti',
             'options': ['Gonfiore', 'Dolore addominale', 'Reflusso', 'Nausea', 'Eruttazione',
                         'Flatulenza', 'Diarrea', 'Stitichezza', 'Alternanza'],
             'required': False, 'report_visible': True},
            {'id': 'pv_gi_frequenza', 'step_id': 's_esame', 'type': 'radio',
             'label': 'Frequenza dei sintomi gastrointestinali',
             'options': ['Mai', 'Occasionale', 'Frequente', 'Quotidiana'],
             'required': False, 'report_visible': True},
            {'id': 'pv_sonno_ore', 'step_id': 's_esame', 'type': 'metrica',
             'label': 'Ore medie di sonno per notte', 'unit': 'h',
             'required': False, 'report_visible': True},
            {'id': 'pv_sonno_qualita', 'step_id': 's_esame', 'type': 'media',
             'label': 'Qualità del sonno percepita', 'min': 1, 'max': 10,
             'minLabel': 'Pessima', 'maxLabel': 'Ottima', 'required': False, 'report_visible': True},
            {'id': 'pv_sonno_difficolta', 'step_id': 's_esame', 'type': 'radio',
             'label': 'Difficoltà ad addormentarsi o risvegli notturni',
             'options': ['No', 'A volte', 'Spesso'], 'required': False, 'report_visible': True},
            {'id': 'pv_stress_livello', 'step_id': 's_esame', 'type': 'media',
             'label': "Livello di stress percepito nell'ultimo mese", 'min': 1, 'max': 10,
             'minLabel': 'Basso', 'maxLabel': 'Alto', 'required': False, 'report_visible': True},
            {'id': 'pv_stress_fonti', 'step_id': 's_esame', 'type': 'checkbox',
             'label': 'Principali fonti di stress',
             'options': ['Lavoro', 'Studio', 'Relazioni', 'Salute', 'Economiche', 'Allenamento / gara', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_stress_cibo', 'step_id': 's_esame', 'type': 'radio',
             'label': 'Lo stress influenza il tuo modo di mangiare?',
             'options': ['Lo riduce', 'Lo aumenta', 'Nessun effetto'],
             'required': False, 'report_visible': True},

            # ── 5 · Storia alimentare e abitudini ─────────────────────
            {'id': 'pv_ab_pasti', 'step_id': 's_alimentare', 'type': 'metrica',
             'label': 'Numero di pasti principali al giorno', 'unit': 'n/die',
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_spuntini', 'step_id': 's_alimentare', 'type': 'metrica',
             'label': 'Numero di spuntini al giorno', 'unit': 'n/die',
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_salti', 'step_id': 's_alimentare', 'type': 'radio',
             'label': 'Salti pasti regolarmente?', 'options': ['Mai', 'A volte', 'Spesso'],
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_salti_dett', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Se salti pasti: quale e perché', 'placeholder': 'Pasto saltato più spesso e motivo…',
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_fuori', 'step_id': 's_alimentare', 'type': 'metrica',
             'label': 'Pasti fuori casa o da asporto a settimana', 'unit': 'n/sett',
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_idratazione', 'step_id': 's_alimentare', 'type': 'metrica',
             'label': 'Idratazione media giornaliera', 'unit': 'L/die',
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_alcol', 'step_id': 's_alimentare', 'type': 'radio',
             'label': 'Consumo di alcol', 'options': ['Mai', 'Occasionale', 'Settimanale', 'Quotidiano'],
             'required': False, 'report_visible': True},
            {'id': 'pv_ab_alcol_qta', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Alcol — quantità e tipo (se presente)', 'placeholder': 'Es. 2 calici di vino nel weekend…',
             'required': False, 'report_visible': True},
            {'id': 'pv_app_approccio', 'step_id': 's_alimentare', 'type': 'checkbox',
             'label': 'Approccio alimentare attuale',
             'options': ['Ipocalorica', 'Ipercalorica', 'Chetogenica', 'Digiuno intermittente',
                         'Conta macro', 'Plant-based', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_app_regime', 'step_id': 's_alimentare', 'type': 'radio',
             'label': 'Regime alimentare', 'options': ['Onnivoro', 'Vegetariano', 'Vegano', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_colazione', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Colazione', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_spuntino_am', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Spuntino mattina', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_pranzo', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Pranzo', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_pre', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Pre-workout', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_post', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Intra / Post-workout', 'placeholder': 'Alimenti, integratori e quantità…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_cena', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Cena', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},
            {'id': 'pv_recall_sera', 'step_id': 's_alimentare', 'type': 'aperta',
             'label': 'Recall · Dopo cena / serale', 'placeholder': 'Alimenti e quantità indicative…',
             'required': False, 'report_visible': True},

            # ── 6 · Storico di diete precedenti ───────────────────────
            {'id': 'pv_diete_passate', 'step_id': 's_diete', 'type': 'checkbox',
             'label': 'Diete o approcci seguiti in passato',
             'options': ['Ipocalorica', 'Ipercalorica', 'Chetogenica', 'Digiuno intermittente',
                         'Conta macro', 'Plant-based', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_diete_risultati', 'step_id': 's_diete', 'type': 'aperta',
             'label': 'Risultati ottenuti e mantenuti nel tempo', 'placeholder': 'Cosa hai ottenuto e per quanto…',
             'required': False, 'report_visible': True},
            {'id': 'pv_diete_cicli', 'step_id': 's_diete', 'type': 'si_no',
             'label': 'Cicli ripetuti di perdita e recupero di peso?',
             'required': False, 'report_visible': True},
            {'id': 'pv_diete_funzionato', 'step_id': 's_diete', 'type': 'aperta',
             'label': 'Cosa ha funzionato in passato', 'placeholder': 'Strategie, abitudini, contesti che hanno funzionato…',
             'required': False, 'report_visible': True},
            {'id': 'pv_diete_non_funzionato', 'step_id': 's_diete', 'type': 'aperta',
             'label': 'Cosa non ha funzionato o hai vissuto male',
             'placeholder': 'Approcci abbandonati, difficoltà, vissuti negativi…',
             'required': False, 'report_visible': True},

            # ── 7 · Obiettivi ─────────────────────────────────────────
            {'id': 'pv_obj_primario', 'step_id': 's_obiettivi', 'type': 'radio',
             'label': 'Obiettivo primario',
             'options': ['Composizione corporea', 'Performance', 'Salute e benessere',
                         'Gestione patologia', 'Rapporto col cibo'],
             'required': False, 'report_visible': True},
            {'id': 'pv_obj_secondari', 'step_id': 's_obiettivi', 'type': 'checkbox',
             'label': 'Obiettivi secondari',
             'options': ['Aumento massa muscolare', 'Riduzione massa grassa', 'Forza',
                         'Resistenza', 'Recupero', 'Salute', 'Altro'],
             'required': False, 'report_visible': True},
            {'id': 'pv_obj_descrizione', 'step_id': 's_obiettivi', 'type': 'aperta',
             'label': 'Descrivi il risultato che vorresti ottenere',
             'placeholder': 'Con parole tue, il risultato ideale…', 'required': False, 'report_visible': True},
            {'id': 'pv_obj_evento', 'step_id': 's_obiettivi', 'type': 'si_no',
             'label': 'Hai una gara, una scadenza o un evento specifico?',
             'required': False, 'report_visible': True},
            {'id': 'pv_obj_evento_data', 'step_id': 's_obiettivi', 'type': 'aperta',
             'label': 'Data della gara / scadenza (se presente)', 'placeholder': 'gg/mm/aaaa',
             'required': False, 'report_visible': True},
            {'id': 'pv_obj_tentativi', 'step_id': 's_obiettivi', 'type': 'aperta',
             'label': 'Hai già provato a raggiungere questo obiettivo in passato? Con quali risultati?',
             'placeholder': 'Tentativi precedenti ed esiti…', 'required': False, 'report_visible': True},

            # ── 8 · Calcolo fabbisogni (strumento interno) ────────────
            {'id': 'tool_fabbisogni', 'step_id': 's_fabbisogni', 'type': 'strumento_fabbisogni',
             'label': 'Calcolo Fabbisogni', 'tool': 'fabbisogni', 'report_visible': True},
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    'completo_coach': {
        'title': 'Completo coach',
        'description': 'Check completo con antropometria, benessere, aderenza, note e foto progressi.',
        'steps': [
            {'id': 's_antrop',     'label': 'Antropometria', 'icon': 'ph-ruler'},
            {'id': 's_benessere',  'label': 'Benessere',     'icon': 'ph-smiley'},
            {'id': 's_note',       'label': 'Note',          'icon': 'ph-note-pencil'},
            {'id': 's_foto',       'label': 'Foto',          'icon': 'ph-camera'},
            {'id': 's_fabbisogni', 'label': 'Fabbisogni',    'icon': 'ph-calculator'},
        ],
        'questions': [
            {'id': 'antropometria', 'step_id': 's_antrop', 'type': 'antropometria', 'label': 'Antropometria',
             'weight': True,
             'circumferences': ['chest', 'waist', 'gluteal', 'arm_relaxed_l', 'arm_relaxed_r', 'thigh_l', 'thigh_r'],
             'skinfolds': ['triceps', 'subscapular', 'suprailiac', 'abdominal'],
             'required': True, 'report_visible': True},
            {'id': 'benessere_umore',   'step_id': 's_benessere', 'type': 'media',   'label': 'Umore generale',        'min': 1, 'max': 5, 'minLabel': 'Pessimo',    'maxLabel': 'Eccellente', 'required': True,  'report_visible': True},
            {'id': 'benessere_sonno',   'step_id': 's_benessere', 'type': 'media',   'label': 'Qualità del sonno',     'min': 1, 'max': 5, 'minLabel': 'Pessima',    'maxLabel': 'Ottima',     'required': False, 'report_visible': True},
            {'id': 'benessere_dieta',   'step_id': 's_benessere', 'type': 'media',   'label': 'Aderenza alla dieta',   'min': 1, 'max': 5, 'minLabel': 'Non seguita','maxLabel': 'Perfetta',   'required': True,  'report_visible': True},
            {'id': 'benessere_workout', 'step_id': 's_benessere', 'type': 'media',   'label': 'Aderenza allenamento',  'min': 1, 'max': 5, 'minLabel': 'Non seguito','maxLabel': 'Perfetto',   'required': True,  'report_visible': True},
            {'id': 'note_infortuni',    'step_id': 's_note',      'type': 'aperta',  'label': 'Infortuni o dolori',    'placeholder': 'Eventuali dolori, tensioni o infortuni...',  'required': False, 'report_visible': True},
            {'id': 'note_limitazioni',  'step_id': 's_note',      'type': 'aperta',  'label': 'Limitazioni o adattamenti', 'placeholder': 'Hai saltato sessioni? Modificato esercizi?', 'required': False, 'report_visible': True},
            {'id': 'note_messaggio',    'step_id': 's_note',      'type': 'aperta',  'label': 'Messaggio al coach',    'placeholder': 'Tutto quello che vuoi condividere...', 'required': False, 'report_visible': False},
            {'id': 'foto_progressi',    'step_id': 's_foto',      'type': 'allegato','label': 'Foto progressi (frontale, laterale, posteriore)', 'required': False, 'report_visible': True},
            {'id': 'tool_fabbisogni',   'step_id': 's_fabbisogni','type': 'strumento_fabbisogni', 'label': 'Calcolo Fabbisogni', 'tool': 'fabbisogni', 'report_visible': True},
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    'rapido_atleta': {
        'title': 'Rapido atleta',
        'description': 'Check breve: peso, umore, sonno, aderenza. Per check-in settimanali veloci.',
        'steps': [
            {'id': 's_main', 'label': 'Check rapido', 'icon': 'ph-lightning'},
        ],
        'questions': [
            {'id': 'peso',     'step_id': 's_main', 'type': 'antropometria', 'label': 'Peso corporeo',
             'weight': True, 'circumferences': [], 'skinfolds': [],
             'required': True, 'report_visible': True},
            {'id': 'umore',    'step_id': 's_main', 'type': 'media',   'label': 'Umore',                'min': 1, 'max': 5, 'minLabel': 'Pessimo',   'maxLabel': 'Eccellente', 'required': True, 'report_visible': True},
            {'id': 'sonno',    'step_id': 's_main', 'type': 'media',   'label': 'Sonno',                'min': 1, 'max': 5, 'minLabel': 'Pessimo',   'maxLabel': 'Ottimo',     'required': True, 'report_visible': True},
            {'id': 'energia',  'step_id': 's_main', 'type': 'media',   'label': 'Livello di energia',   'min': 1, 'max': 5, 'minLabel': 'Esausto',   'maxLabel': 'Carico',     'required': False,'report_visible': True},
            {'id': 'dieta',    'step_id': 's_main', 'type': 'media',   'label': 'Aderenza dieta',       'min': 1, 'max': 5, 'minLabel': 'Non seguita','maxLabel': 'Perfetta',  'required': True, 'report_visible': True},
            {'id': 'workout',  'step_id': 's_main', 'type': 'media',   'label': 'Aderenza allenamento', 'min': 1, 'max': 5, 'minLabel': 'Non seguito','maxLabel': 'Perfetto',  'required': True, 'report_visible': True},
            {'id': 'note',     'step_id': 's_main', 'type': 'aperta',  'label': 'Note',                 'placeholder': 'Qualcosa da segnalare?', 'required': False, 'report_visible': False},
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    'feedback_atleta': {
        'title': 'Feedback atleta',
        'description': 'Questionario di feedback sulla qualità del servizio e dell\'esperienza di coaching.',
        'steps': [
            {'id': 's_servizio',  'label': 'Servizio',   'icon': 'ph-star'},
            {'id': 's_programma', 'label': 'Programma',  'icon': 'ph-barbell'},
            {'id': 's_suggest',   'label': 'Suggerimenti','icon': 'ph-chat-circle-text'},
        ],
        'questions': [
            {'id': 'soddisfazione',     'step_id': 's_servizio',  'type': 'media',   'label': 'Soddisfazione generale',         'min': 1, 'max': 10, 'minLabel': 'Bassa', 'maxLabel': 'Alta', 'required': True, 'report_visible': True},
            {'id': 'comunicazione',     'step_id': 's_servizio',  'type': 'media',   'label': 'Comunicazione del coach',        'min': 1, 'max': 10, 'minLabel': 'Scarsa','maxLabel': 'Ottima','required': True,'report_visible': True},
            {'id': 'consiglieresti',    'step_id': 's_servizio',  'type': 'si_no',   'label': 'Consiglieresti il servizio?',                                                        'required': True, 'report_visible': True},
            {'id': 'difficolta',        'step_id': 's_programma', 'type': 'radio',   'label': 'Difficoltà percepita del programma', 'options': ['Troppo facile','Adeguata','Troppo difficile'], 'required': True, 'report_visible': True},
            {'id': 'risultati',         'step_id': 's_programma', 'type': 'media',   'label': 'Risultati ottenuti',             'min': 1, 'max': 10, 'minLabel': 'Nessuno','maxLabel': 'Eccellenti','required': True,'report_visible': True},
            {'id': 'aree_miglioramento','step_id': 's_programma', 'type': 'checkbox','label': 'Aree da migliorare',             'options': ['Programmazione','Comunicazione','Tempi di risposta','Materiale didattico','Frequenza check'], 'required': False,'report_visible': True},
            {'id': 'punto_forza',       'step_id': 's_suggest',   'type': 'aperta',  'label': 'Cosa apprezzi di più?',           'placeholder': 'Punti di forza...', 'required': False, 'report_visible': True},
            {'id': 'suggerimenti',      'step_id': 's_suggest',   'type': 'aperta',  'label': 'Suggerimenti per migliorare',     'placeholder': 'Cosa cambieresti?', 'required': False, 'report_visible': True},
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    'nutrizione': {
        'title': 'Nutrizione',
        'description': 'Check nutrizionale: composizione corporea, abitudini alimentari, idratazione.',
        'steps': [
            {'id': 's_compos',     'label': 'Composizione', 'icon': 'ph-scales'},
            {'id': 's_abitudini',  'label': 'Abitudini',    'icon': 'ph-fork-knife'},
            {'id': 's_diario',     'label': 'Diario',       'icon': 'ph-notebook'},
            {'id': 's_fabbisogni', 'label': 'Fabbisogni',   'icon': 'ph-calculator'},
        ],
        'questions': [
            {'id': 'antropometria',  'step_id': 's_compos',    'type': 'antropometria', 'label': 'Antropometria',
             'weight': True,
             'circumferences': ['waist', 'gluteal'],
             'skinfolds': ['abdominal'],
             'required': True, 'report_visible': True},
            {'id': 'aderenza_dieta', 'step_id': 's_abitudini', 'type': 'media',   'label': 'Aderenza al piano',       'min': 1, 'max': 10, 'minLabel': 'Nulla','maxLabel': 'Totale', 'required': True, 'report_visible': True},
            {'id': 'pasti_fuori',    'step_id': 's_abitudini', 'type': 'metrica', 'label': 'Pasti fuori casa',        'unit': 'n/sett', 'required': False, 'report_visible': True},
            {'id': 'sgarri',         'step_id': 's_abitudini', 'type': 'metrica', 'label': 'Sgarri programmati',      'unit': 'n/sett', 'required': False, 'report_visible': True},
            {'id': 'idratazione',    'step_id': 's_abitudini', 'type': 'metrica', 'label': 'Acqua assunta',           'unit': 'L/die', 'required': False, 'report_visible': True},
            {'id': 'fame',           'step_id': 's_abitudini', 'type': 'media',   'label': 'Senso di fame',           'min': 1, 'max': 5, 'minLabel': 'Mai','maxLabel': 'Costante', 'required': False, 'report_visible': True},
            {'id': 'digestione',     'step_id': 's_abitudini', 'type': 'radio',   'label': 'Digestione',               'options': ['Ottima','Buona','Discreta','Difficoltosa'], 'required': False, 'report_visible': True},
            {'id': 'integratori',    'step_id': 's_abitudini', 'type': 'checkbox','label': 'Integratori assunti',     'options': ['Proteine','Creatina','Multivitaminico','Omega 3','Vitamina D','Magnesio','Altro'], 'required': False, 'report_visible': True},
            {'id': 'diario',         'step_id': 's_diario',    'type': 'allegato','label': 'Diario alimentare (foto/PDF)', 'required': False, 'report_visible': True},
            {'id': 'note',           'step_id': 's_diario',    'type': 'aperta',  'label': 'Note al nutrizionista',   'placeholder': 'Difficoltà, dubbi, segnalazioni...', 'required': False, 'report_visible': False},
            {'id': 'tool_fabbisogni','step_id': 's_fabbisogni','type': 'strumento_fabbisogni', 'label': 'Calcolo Fabbisogni', 'tool': 'fabbisogni', 'report_visible': True},
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    'allenamento': {
        'title': 'Allenamento',
        'description': 'Check allenamento: aderenza, performance, recupero, dolori articolari.',
        'steps': [
            {'id': 's_aderenza',  'label': 'Aderenza',    'icon': 'ph-check-square'},
            {'id': 's_perf',      'label': 'Performance', 'icon': 'ph-chart-line-up'},
            {'id': 's_recupero',  'label': 'Recupero',    'icon': 'ph-moon'},
        ],
        'questions': [
            {'id': 'sessioni_fatte', 'step_id': 's_aderenza', 'type': 'metrica', 'label': 'Sessioni completate',     'unit': 'n', 'required': True, 'report_visible': True},
            {'id': 'sessioni_target','step_id': 's_aderenza', 'type': 'metrica', 'label': 'Sessioni programmate',    'unit': 'n', 'required': True, 'report_visible': True},
            {'id': 'aderenza_pct',   'step_id': 's_aderenza', 'type': 'media',   'label': 'Aderenza al programma',    'min': 1, 'max': 10, 'minLabel': 'Nulla', 'maxLabel': 'Totale', 'required': True, 'report_visible': True},
            {'id': 'esercizi_skip',  'step_id': 's_aderenza', 'type': 'aperta',  'label': 'Esercizi saltati o modificati', 'placeholder': 'Quali e perché?', 'required': False, 'report_visible': True},
            {'id': 'percezione_pr',  'step_id': 's_perf',     'type': 'si_no',   'label': 'Ottenuti PR questa settimana?', 'required': False, 'report_visible': True},
            {'id': 'rpe_medio',      'step_id': 's_perf',     'type': 'media',   'label': 'RPE medio sessioni',       'min': 1, 'max': 10, 'minLabel': '1', 'maxLabel': '10', 'required': True, 'report_visible': True},
            {'id': 'energia_palestra','step_id': 's_perf',    'type': 'media',   'label': 'Energia in palestra',      'min': 1, 'max': 5, 'minLabel': 'Esausto','maxLabel': 'Carico','required': True,'report_visible': True},
            {'id': 'note_perf',      'step_id': 's_perf',     'type': 'aperta',  'label': 'Note tecniche / esecuzione','placeholder': 'Cosa è andato bene/male?', 'required': False, 'report_visible': True},
            {'id': 'doms',           'step_id': 's_recupero', 'type': 'media',   'label': 'DOMS (indolenzimento)',    'min': 1, 'max': 5, 'minLabel': 'Nessuno','maxLabel': 'Severo','required': False,'report_visible': True},
            {'id': 'sonno_ore',      'step_id': 's_recupero', 'type': 'metrica', 'label': 'Ore di sonno medie',       'unit': 'h', 'required': False, 'report_visible': True},
            {'id': 'stress',         'step_id': 's_recupero', 'type': 'media',   'label': 'Stress percepito',         'min': 1, 'max': 5, 'minLabel': 'Basso','maxLabel': 'Alto','required': False,'report_visible': True},
            {'id': 'dolori',         'step_id': 's_recupero', 'type': 'checkbox','label': 'Dolori articolari',        'options': ['Spalle','Gomiti','Polsi','Schiena bassa','Ginocchia','Anche','Caviglie','Nessuno'], 'required': False, 'report_visible': True},
        ],
    },
}


def build_template_payload(preset_key: str) -> dict:
    """Return a dict suitable for QuestionnaireTemplate.objects.create defaults."""
    preset = PRESETS[preset_key]
    return {
        'title': preset['title'],
        'description': preset.get('description', ''),
        'questionnaire_type': 'preset_' + preset_key,
        'is_active': True,
        'preset_key': preset_key,
        'is_modified_preset': False,
        'steps_config': preset['steps'],
        'questions_config': preset['questions'],
    }
