# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['client', 'status'], name='billing_cli_client__fd899b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['subscription_plan', 'status'], name='billing_cli_subscri_dc78cc_idx'),
        ),
    ]
