# Generated by Django 6.0.4 on 2026-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_clientsubscription_billing_cli_client__fd899b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
