# Generated by Django 6.0.4 on 2026-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_clientsubscription_expiry_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent', models.CharField(blank=True, default='', max_length=255)),
                ('amount_total', models.IntegerField(default=0)),
                ('currency', models.CharField(default='eur', max_length=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
