# Generated by Django 6.0.4 on 2026-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_platformpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpurchase',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='has_chiron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='plan',
            field=models.CharField(choices=[('athena', 'Athena'), ('apollo', 'Apollo'), ('zeus', 'Zeus')], default='apollo', max_length=20),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
