# Generated by Django 6.0.4 on 2026-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_platformpurchase_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpurchase',
            name='billing_interval',
            field=models.CharField(choices=[('mensile', 'Mensile'), ('annuale', 'Annuale')], default='mensile', max_length=10),
        ),
    ]
