# Generated by Django 6.0.4 on 2026-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coachprofile_platform_purchase'),
        ('billing', '0006_platformpurchase_billing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpurchase',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_purchases_redeemed', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='platformpurchase',
            name='returning_customer',
            field=models.BooleanField(default=False),
        ),
    ]
