# Generated by Django 6.0.4 on 2026-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_stripeconnectevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GBP', 'Sterlina (£)'), ('USD', 'Dollaro USA ($)'), ('JPY', 'Yen (¥)')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('mensile', 'Mensile'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GBP', 'Sterlina (£)'), ('USD', 'Dollaro USA ($)'), ('JPY', 'Yen (¥)')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('mensile', 'Mensile'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale'), ('una_tantum', 'Una Tantum')], default='mensile', max_length=100),
        ),
    ]
