# Generated by Django 6.0.4 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coachprofile_professional_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='professional_videos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='coach_photos/'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_tiktok',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_youtube',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
