# Generated by Django 6.0.4 on 2026-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='client_photos/'),
        ),
    ]
