# Generated by Django 6.0.4 on 2026-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clientprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
