# Generated by Django 6.0.4 on 2026-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='calendar_feed_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
