# Generated by Django 6.0.4 on 2026-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chiron_intro_seen',
            field=models.BooleanField(default=False),
        ),
    ]
