# Generated by Django 6.0.4 on 2026-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_chiron_intro_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
