# Generated by Django 6.0.4 on 2026-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_internal_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_test_account',
            field=models.BooleanField(default=False),
        ),
    ]
