# Generated by Django 6.0.4 on 2026-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_internal_user_user_is_test_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='bundle_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
