# Generated by Django 6.0.4 on 2026-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_coachprofile_custom_bmr_formulas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='primary_goal',
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='professional_type',
            field=models.CharField(choices=[('COACH', 'Coach'), ('NUTRIZIONISTA', 'Nutrizionista'), ('ALLENATORE', 'Allenatore'), ('ALTRO', 'Altro')], default='COACH', max_length=20),
        ),
    ]
