# Generated by Django 6.0.4 on 2026-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_terms_accepted_at_user_terms_version'),
        ('billing', '0006_platformpurchase_billing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='platform_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_profiles', to='billing.platformpurchase'),
        ),
    ]
