# Generated by Django 6.0.4 on 2026-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coachprofile_platform_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='stripe_connect_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='stripe_connect_onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
