# Generated by Django 6.0.4 on 2026-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_coachprofile_stripe_connect_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_accent',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_primary',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
