# Generated by Django 6.0.7 on 2026-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_brand_accent_user_brand_name_user_brand_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='calendar_feed_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
