# Generated by Django 6.0.4 on 2026-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_clientprofile_calendar_feed_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
