# Generated by Django 6.0.4 on 2026-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='load_unit',
            field=models.CharField(blank=True, choices=[('KG', 'kg'), ('PERCENT_1RM', '% 1RM'), ('BODYWEIGHT', 'corpo libero')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='load_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='superset_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='frequency_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='last_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bozza'), ('TEMPLATE', 'Template'), ('ACTIVE', 'Attiva')], default='DRAFT', max_length=20),
        ),
    ]
