# Generated by Django 6.0.4 on 2026-05-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutsession_sessionmedia_sessioncoachnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='alternative_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_alternative', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='workoutsetlog',
            name='actual_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_in_set_logs', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='workoutsetlog',
            name='exercise_substituted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutsetlog',
            name='is_extra_set',
            field=models.BooleanField(default=False),
        ),
    ]
