# Generated by Django 6.0.4 on 2026-05-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_alternative_exercises_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
