# Generated by Django 6.0.4 on 2026-05-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutplan_duration_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('family', models.CharField(choices=[('LOAD', 'Carico'), ('VOLUME', 'Volume'), ('INTENSITY', 'Intensità'), ('DENSITY', 'Densità'), ('TEMPO', 'Tempo'), ('ROM', 'ROM'), ('VARIANT', 'Variante'), ('FREQUENCY', 'Frequenza'), ('UNDULATION', 'Ondulazione'), ('DELOAD', 'Deload'), ('VELOCITY', 'Velocità')], max_length=20)),
                ('subtype', models.CharField(choices=[('LOAD_LINEAR', 'Carico lineare'), ('LOAD_PERCENT', 'Carico percentuale'), ('LOAD_MICRO', 'Micro-load'), ('LOAD_MANUAL', 'Carico manuale per settimana'), ('LOAD_TOP_BACKOFF', 'Top set / Back-off'), ('VOL_SETS', 'Progressione serie'), ('VOL_REPS', 'Progressione reps'), ('VOL_SETS_REPS', 'Serie + reps combinate'), ('VOL_DOUBLE', 'Double progression'), ('VOL_TRIPLE', 'Triple progression'), ('INT_RPE', 'RPE progressivo'), ('INT_RIR', 'RIR progressivo'), ('INT_PCT1RM', '% 1RM per settimana'), ('DEN_REST', 'Riduzione recupero'), ('DEN_TIME', 'Densità tempo'), ('TEMPO_PRESET', 'Preset tempo'), ('TEMPO_ECC', 'Tempo eccentrico'), ('TEMPO_CON', 'Tempo concentrico'), ('TEMPO_PAUSE', 'Pausa isometrica'), ('ROM_INCREASE', 'Aumento ROM'), ('ROM_DEFICIT', 'Deficit / rialzo'), ('ROM_PAUSE', 'Pausa in allungamento'), ('VAR_TRANSITION', 'Transizione variante'), ('FREQ_ADD', 'Aumento frequenza'), ('UND_WUP', 'WUP — Ondulata settimanale'), ('UND_DUP', 'DUP — Ondulata giornaliera'), ('UND_BLOCK', 'Periodizzazione a blocchi'), ('DEL_AUTO', 'Deload automatico'), ('DEL_MANUAL', 'Deload manuale'), ('VEL_TARGET', 'Target velocità'), ('VEL_RANGE', 'Range velocità')], max_length=40)),
                ('target_metric', models.CharField(choices=[('load', 'Carico'), ('sets', 'Serie'), ('reps', 'Ripetizioni'), ('rep_range', 'Range ripetizioni'), ('rpe', 'RPE'), ('rir', 'RIR'), ('rest', 'Recupero'), ('tempo', 'Tempo'), ('rom', 'ROM'), ('duration', 'Durata'), ('exercise_variant', 'Variante'), ('frequency', 'Frequenza'), ('velocity', 'Velocità'), ('notes', 'Note')], max_length=30)),
                ('application_mode', models.CharField(choices=[('FIXED_INCREMENT', 'Incremento fisso'), ('PERCENT_INCREMENT', 'Incremento percentuale'), ('EXPLICIT_VALUES', 'Valori espliciti'), ('RULE_BASED', 'Basato su regola'), ('MILESTONE_BASED', 'Basato su milestone'), ('MANUAL_OVERRIDE', 'Override manuale')], default='FIXED_INCREMENT', max_length=30)),
                ('start_week', models.PositiveIntegerField(default=1)),
                ('end_week', models.PositiveIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('stackable', models.BooleanField(default=True)),
                ('conflict_strategy', models.CharField(choices=[('LAST_WINS', 'Ultimo prevale'), ('ADD', 'Somma'), ('MULTIPLY', 'Moltiplica'), ('REPLACE', 'Sostituisce'), ('ERROR', 'Errore')], default='LAST_WINS', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_rules', to='workouts.workoutexercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_rules', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['workout_exercise_id', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseVariantTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_transition_targets', to='workouts.exercise')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_transitions', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['workout_exercise_id', 'week_number'],
                'unique_together': {('workout_exercise', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeekDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('week_type', models.CharField(choices=[('STANDARD', 'Standard'), ('DELOAD', 'Deload'), ('TEST', 'Test'), ('TECHNIQUE', 'Tecnica'), ('RECOVERY', 'Recovery')], default='STANDARD', max_length=20)),
                ('preset', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('workout_plan', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('metric', models.CharField(choices=[('load', 'Carico'), ('sets', 'Serie'), ('reps', 'Ripetizioni'), ('rep_range', 'Range ripetizioni'), ('rpe', 'RPE'), ('rir', 'RIR'), ('rest', 'Recupero'), ('tempo', 'Tempo'), ('rom', 'ROM'), ('duration', 'Durata'), ('exercise_variant', 'Variante'), ('frequency', 'Frequenza'), ('velocity', 'Velocità'), ('notes', 'Note')], max_length=30)),
                ('value_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_overrides', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['workout_exercise_id', 'week_number', 'metric'],
                'unique_together': {('workout_exercise', 'week_number', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('load_unit', models.CharField(blank=True, default='', max_length=20)),
                ('set_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rep_range', models.CharField(blank=True, default='', max_length=32)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recovery_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, default='', max_length=10)),
                ('rom_stage', models.CharField(blank=True, default='', max_length=20)),
                ('velocity_target', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_override', models.BooleanField(default=False)),
                ('is_deload', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('variant_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_value_variants', to='workouts.exercise')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_values', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['workout_exercise_id', 'week_number'],
                'indexes': [models.Index(fields=['workout_exercise', 'week_number'], name='workouts_we_workout_6f0905_idx')],
                'unique_together': {('workout_exercise', 'week_number')},
            },
        ),
    ]
