# Generated by Django 6.0.4 on 2026-05-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clientprofile_profile_image'),
        ('workouts', '0007_progressionrule_exercisevarianttransition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('region', models.CharField(choices=[('UPPER', 'Parte superiore'), ('LOWER', 'Parte inferiore'), ('CORE', 'Core')], default='UPPER', max_length=10)),
                ('color_token', models.CharField(blank=True, default='', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['region', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='coach_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/covers/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to='accounts.coachprofile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_kind',
            field=models.CharField(choices=[('WEEKLY', 'Scheda settimanale'), ('PROGRAM', 'Programmazione')], default='WEEKLY', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ManyToManyField(blank=True, related_name='exercises_primary', to='workouts.musclegroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='exercises_secondary', to='workouts.musclegroup'),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('category', models.CharField(choices=[('FORCE', 'Forza'), ('TEAM', 'Squadra'), ('ENDURANCE', 'Endurance'), ('COMBAT', 'Combattimento'), ('RACKET', 'Racchetta'), ('OTHER', 'Altro')], default='OTHER', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_created', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='workouts.sport'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='workouts.sport'),
        ),
        migrations.CreateModel(
            name='WorkoutFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('label_text', models.CharField(blank=True, default='', max_length=40)),
                ('label_color', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_folders', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('coach', 'title')},
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='workouts.workoutfolder'),
        ),
    ]
