# Generated by Django 6.0.4 on 2026-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_remap_anatomical_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='starts_at_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
