# Generated by Django 6.0.4 on 2026-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_workoutexercise_starts_at_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='ends_at_week',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='inactive_weeks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
