# Generated by Django 6.0.4 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_token'),
        ('workouts', '0012_workoutexercise_ends_at_week_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workoutassignment',
            index=models.Index(fields=['client', 'coach', 'status'], name='workouts_wo_client__dc85a8_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutassignment',
            index=models.Index(fields=['coach', '-created_at'], name='workouts_wo_coach_i_6c95d3_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['client', '-workout_date'], name='workouts_wo_client__3c7ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['workout_assignment', '-workout_date'], name='workouts_wo_workout_b47867_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['client', '-started_at'], name='workouts_wo_client__0a1bae_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['assignment', 'completed'], name='workouts_wo_assignm_32341e_idx'),
        ),
    ]
