# Generated by Django 6.0.4 on 2026-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workoutassignment_workouts_wo_client__dc85a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='set_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
