# Generated by Django 6.0.4 on 2026-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_terms_accepted_at_user_terms_version'),
        ('workouts', '0014_workoutexercise_set_details'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['coach', 'status'], name='workouts_wo_coach_i_ee0c61_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['coach', 'is_template'], name='workouts_wo_coach_i_786401_idx'),
        ),
    ]
