# Generated by Django 6.0.4 on 2026-07-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_workoutplan_workouts_wo_coach_i_ee0c61_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutsetlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workoutsetlog',
            name='workout_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutexercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutsetlog',
            constraint=models.UniqueConstraint(condition=models.Q(('workout_exercise__isnull', False)), fields=('session', 'workout_exercise', 'set_number'), name='uniq_setlog_planned'),
        ),
        migrations.AddConstraint(
            model_name='workoutsetlog',
            constraint=models.UniqueConstraint(condition=models.Q(('workout_exercise__isnull', True)), fields=('session', 'actual_exercise', 'set_number'), name='uniq_setlog_added'),
        ),
    ]
