# Generated by Django 6.0.4 on 2026-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_alter_workoutsetlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutassignment',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('WEEKS', 'settimane'), ('MONTHS', 'mesi')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='duration_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
