# Generated by Django 6.0.4 on 2026-07-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_workoutassignment_duration_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.IntegerField(unique=True)),
                ('name_en', models.CharField(max_length=60)),
                ('name_it', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name_it'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.IntegerField(unique=True)),
                ('name_en', models.CharField(max_length=60)),
                ('name_it', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name_it'],
            },
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='body_region',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_classification',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='movement_pattern_1',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='movement_pattern_2',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='aliases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='license_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='license_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='wger_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='wger_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='wger_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.exercisecategory'),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='workouts.equipment'),
        ),
    ]
